// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import {
  Plus,
  Pencil,
  Trash2,
  X,
  FileText,
  ImagePlus,
  XCircle,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const EMPTY_FORM = {
  title: "",
  body: "",
  author: "",
  category: "",
  date: "",
  cover: null,
};

/**
 * ManageArticles — Admin CRUD panel for Articles.
 * Handles Add, Edit, Delete operations against /api/articles/* endpoints.
 */
export default function ManageArticles() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false);
  const [editTarget, setEditTarget] = useState(null);
  const [form, setForm] = useState(EMPTY_FORM);
  const [coverPreview, setCoverPreview] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [deleteId, setDeleteId] = useState(null);

  // ── Fetch ──────────────────────────────────────────────────────────
  const fetchArticles = async () => {
    try {
      setLoading(true);
      const res = await axios.get("http://localhost:3005/api/articles/all");
      setArticles(res.data.data || []);
    } catch {
      toast.error("Failed to load articles");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchArticles();
  }, []);

  // ── Helpers ────────────────────────────────────────────────────────
  const todayValue = () => new Date().toISOString().split("T")[0];

  const openAdd = () => {
    setEditTarget(null);
    setForm({ ...EMPTY_FORM, date: todayValue() });
    setCoverPreview("");
    setFormOpen(true);
  };

  const openEdit = (article) => {
    setEditTarget(article);
    setForm({
      title: article.title,
      body: article.body,
      author: article.author,
      category: article.category,
      date: article.date
        ? new Date(article.date).toISOString().split("T")[0]
        : todayValue(),
      cover: null,
    });
    setCoverPreview(article.cover || "");
    setFormOpen(true);
  };

  const closeForm = () => {
    setFormOpen(false);
    setEditTarget(null);
    setForm(EMPTY_FORM);
    setCoverPreview("");
  };

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (name === "cover" && files?.[0]) {
      setForm((prev) => ({ ...prev, cover: files[0] }));
      setCoverPreview(URL.createObjectURL(files[0]));
    } else {
      setForm((prev) => ({ ...prev, [name]: value }));
    }
  };

  // ── Submit ─────────────────────────────────────────────────────────
  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      const data = new FormData();
      data.append("title", form.title.trim());
      data.append("body", form.body.trim());
      data.append("author", form.author.trim());
      data.append("category", form.category.trim());
      data.append("date", form.date);
      if (form.cover) data.append("cover", form.cover);

      if (editTarget) {
        await axios.put(
          `http://localhost:3005/api/articles/update/${editTarget._id}`,
          data,
        );
        toast.success("Article updated successfully");
      } else {
        await axios.post("http://localhost:3005/api/articles/create", data);
        toast.success("Article added successfully");
      }

      closeForm();
      fetchArticles();
    } catch (err) {
      toast.error(err.response?.data?.message || "Operation failed");
    } finally {
      setSubmitting(false);
    }
  };

  // ── Delete ─────────────────────────────────────────────────────────
  const handleDelete = async () => {
    if (!deleteId) return;
    try {
      await axios.delete(
        `http://localhost:3005/api/articles/delete/${deleteId}`,
      );
      toast.success("Article deleted");
      setDeleteId(null);
      fetchArticles();
    } catch {
      toast.error("Failed to delete article");
    }
  };

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <div>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <FileText size={24} className="text-[#c9a84c]" />
            Manage Articles
          </h2>
          <p className="text-gray-400 text-sm mt-1">
            {articles.length} article{articles.length !== 1 ? "s" : ""} total
          </p>
        </div>
        <button
          onClick={openAdd}
          className="w-full sm:w-auto flex items-center justify-center gap-2 bg-[#c9a84c] hover:bg-[#d8b45a] text-[#0d1b2a] px-4 py-2 rounded-lg font-semibold text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
        >
          <Plus size={16} />
          Add Article
        </button>
      </div>

      {/* Table */}
      {loading ? (
        <p className="text-gray-400 text-center py-16">Loading articles...</p>
      ) : articles.length === 0 ? (
        <p className="text-gray-500 text-center py-16">No articles found</p>
      ) : (
        <>
          {/* Desktop Table */}
          <div className="hidden md:block overflow-x-auto rounded-xl border border-[#c9a84c]/20">
            <table className="w-full text-sm text-left">
              <thead className="bg-[#0a0f1e] text-[#c9a84c] uppercase text-xs">
                <tr>
                  <th className="px-4 py-3">Cover</th>
                  <th className="px-4 py-3">Title</th>
                  <th className="px-4 py-3">Author</th>
                  <th className="px-4 py-3">Category</th>
                  <th className="px-4 py-3">Date</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>

              <tbody>
                {articles.map((article) => (
                  <tr
                    key={article._id}
                    className="bg-[#0d1b2a] border-b border-[#c9a84c]/10"
                  >
                    <td className="px-4 py-3">
                      <img
                        src={article.cover}
                        alt=""
                        className="w-12 h-12 rounded object-cover"
                      />
                    </td>

                    <td className="px-4 py-3">
                      <p className="text-white font-semibold">
                        {article.title}
                      </p>

                      <p className="text-gray-400 text-xs">
                        {article.body?.slice(0, 60)}...
                      </p>
                    </td>

                    <td className="px-4 py-3 text-gray-300">
                      {article.author}
                    </td>

                    <td className="px-4 py-3">
                      <span className="bg-[#c9a84c]/10 text-[#c9a84c] px-2 py-1 rounded-full text-xs">
                        {article.category}
                      </span>
                    </td>

                    <td className="px-4 py-3 text-gray-300">
                      {new Date(article.date).toLocaleDateString()}
                    </td>

                    <td className="px-4 py-3">
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => openEdit(article)}
                          className="text-blue-400"
                        >
                          <Pencil size={16} />
                        </button>

                        <button
                          onClick={() => setDeleteId(article._id)}
                          className="text-red-400"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile Cards */}
          <div className="grid gap-4 md:hidden">
            {articles.map((article) => (
              <div
                key={article._id}
                className="bg-[#0d1b2a] border border-[#c9a84c]/20 rounded-xl p-4"
              >
                <div className="flex gap-3">
                  <img
                    src={article.cover}
                    alt=""
                    className="w-20 h-20 rounded-lg object-cover"
                  />

                  <div className="flex-1">
                    <h3 className="text-white font-semibold text-sm">
                      {article.title}
                    </h3>

                    <p className="text-[#c9a84c] text-xs mt-1">
                      {article.author}
                    </p>

                    <span className="inline-block mt-2 bg-[#c9a84c]/10 text-[#c9a84c] px-2 py-1 rounded-full text-xs">
                      {article.category}
                    </span>
                  </div>
                </div>

                <p className="text-gray-400 text-xs mt-3 line-clamp-3">
                  {article.body}
                </p>

                <div className="flex justify-between items-center mt-4">
                  <span className="text-gray-500 text-xs">
                    {new Date(article.date).toLocaleDateString()}
                  </span>

                  <div className="flex gap-2">
                    <button
                      onClick={() => openEdit(article)}
                      className="p-2 bg-blue-500/10 rounded-lg text-blue-400"
                    >
                      <Pencil size={16} />
                    </button>

                    <button
                      onClick={() => setDeleteId(article._id)}
                      className="p-2 bg-red-500/10 rounded-lg text-red-400"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Add / Edit Form Modal */}
      <AnimatePresence>
        {formOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4"
            role="dialog"
            aria-modal="true"
            aria-labelledby="article-form-title"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-[#0d1b2a] border border-[#c9a84c]/30 rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between mb-5">
                <h3
                  id="article-form-title"
                  className="text-lg font-bold text-white"
                >
                  {editTarget ? "Edit Article" : "Add New Article"}
                </h3>
                <button
                  onClick={closeForm}
                  aria-label="Close form"
                  className="text-gray-400 hover:text-white transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c] rounded"
                >
                  <X size={20} />
                </button>
              </div>

              {/* Form */}
              <form onSubmit={handleSubmit} noValidate className="space-y-4">
                {/* Title */}
                <div>
                  <label
                    htmlFor="article-title"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Title{" "}
                    <span aria-hidden="true" className="text-red-400">
                      *
                    </span>
                  </label>
                  <input
                    id="article-title"
                    name="title"
                    value={form.title}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. Walking in Faith"
                  />
                </div>

                {/* Author */}
                <div>
                  <label
                    htmlFor="article-author"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Author{" "}
                    <span aria-hidden="true" className="text-red-400">
                      *
                    </span>
                  </label>
                  <input
                    id="article-author"
                    name="author"
                    value={form.author}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. Pastor John"
                  />
                </div>

                {/* Category */}
                <div>
                  <label
                    htmlFor="article-category"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Category{" "}
                    <span aria-hidden="true" className="text-red-400">
                      *
                    </span>
                  </label>
                  <input
                    id="article-category"
                    name="category"
                    value={form.category}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. Faith, Prayer, Grace"
                  />
                </div>

                {/* Date */}
                <div>
                  <label
                    htmlFor="article-date"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Date{" "}
                    <span aria-hidden="true" className="text-red-400">
                      *
                    </span>
                  </label>
                  <input
                    id="article-date"
                    name="date"
                    type="date"
                    value={form.date}
                    onChange={handleChange}
                    required
                    max={todayValue()}
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                  />
                </div>

                {/* Body */}
                <div>
                  <label
                    htmlFor="article-body"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Content{" "}
                    <span aria-hidden="true" className="text-red-400">
                      *
                    </span>
                  </label>
                  <textarea
                    id="article-body"
                    name="body"
                    value={form.body}
                    onChange={handleChange}
                    required
                    rows={6}
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors resize-y"
                    placeholder="Write the article content here..."
                  />
                </div>

                {/* Cover Image */}
                <div>
                  <label className="block text-sm text-gray-400 mb-1">
                    Cover Image{" "}
                    {editTarget && (
                      <span className="text-xs text-gray-500">
                        (leave empty to keep current)
                      </span>
                    )}
                  </label>
                  <div className="relative">
                    <label
                      htmlFor="article-cover"
                      className="flex items-center gap-3 cursor-pointer bg-[#0a0f1e] border border-dashed border-[#c9a84c]/40 rounded-lg px-3 py-3 hover:border-[#c9a84c] transition-colors"
                    >
                      {coverPreview ? (
                        <img
                          src={coverPreview}
                          alt="Cover preview"
                          className="w-12 h-12 object-cover rounded"
                        />
                      ) : (
                        <ImagePlus size={28} className="text-[#c9a84c]/50" />
                      )}
                      <span className="text-gray-400 text-sm">
                        {form.cover
                          ? form.cover.name
                          : coverPreview
                            ? "Click to change image"
                            : "Click to upload cover"}
                      </span>
                      <input
                        id="article-cover"
                        name="cover"
                        type="file"
                        accept="image/*"
                        onChange={handleChange}
                        className="sr-only"
                      />
                    </label>
                    {coverPreview && (
                      <button
                        type="button"
                        onClick={() => {
                          setForm((prev) => ({ ...prev, cover: null }));
                          setCoverPreview("");
                        }}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-red-400 transition-colors"
                        aria-label="Remove cover image"
                      >
                        <XCircle size={20} />
                      </button>
                    )}
                  </div>
                </div>

                {/* Actions */}
                <div className="flex gap-3 pt-2">
                  <button
                    type="button"
                    onClick={closeForm}
                    className="flex-1 border border-[#c9a84c]/30 text-gray-300 hover:text-white rounded-lg py-2 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="flex-1 bg-[#c9a84c] hover:bg-[#d8b45a] disabled:opacity-60 disabled:cursor-not-allowed text-[#0d1b2a] font-semibold rounded-lg py-2 text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                  >
                    {submitting
                      ? "Saving..."
                      : editTarget
                        ? "Update Article"
                        : "Add Article"}
                  </button>
                </div>
              </form>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Delete Confirm Modal */}
      <AnimatePresence>
        {deleteId && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4"
            role="dialog"
            aria-modal="true"
            aria-labelledby="delete-article-title"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-[#0d1b2a] border border-red-500/30 rounded-2xl p-6 w-full max-w-sm text-center"
            >
              <Trash2 size={36} className="text-red-400 mx-auto mb-3" />
              <h3
                id="delete-article-title"
                className="text-lg font-bold text-white mb-2"
              >
                Delete Article?
              </h3>
              <p className="text-gray-400 text-sm mb-5">
                This action cannot be undone.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteId(null)}
                  className="flex-1 border border-[#c9a84c]/30 text-gray-300 hover:text-white rounded-lg py-2 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                >
                  Cancel
                </button>
                <button
                  onClick={handleDelete}
                  className="flex-1 bg-red-500 hover:bg-red-600 text-white font-semibold rounded-lg py-2 text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-red-400"
                >
                  Yes, Delete
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
