// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { Plus, Pencil, Trash2, X, BookOpen, ImagePlus } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const EMPTY_FORM = {
  title: "",
  subtitle: "",
  author: "",
  topic: "",
  year: "",
  cover: null,
};

/**
 * ManageBooks — Admin CRUD panel for Books.
 * Handles Add, Edit, Delete operations against /api/books/* endpoints.
 */
export default function ManageBooks() {
  const [books, setBooks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false);
  const [editTarget, setEditTarget] = useState(null); // null = Add mode
  const [form, setForm] = useState(EMPTY_FORM);
  const [coverPreview, setCoverPreview] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [deleteId, setDeleteId] = useState(null);

  // ── Fetch ──────────────────────────────────────────────────────────
  const fetchBooks = async () => {
    try {
      setLoading(true);
      const res = await axios.get("http://localhost:3005/api/books/all");
      setBooks(res.data.data || []);
    } catch {
      toast.error("Failed to load books");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBooks();
  }, []);

  // ── Helpers ────────────────────────────────────────────────────────
  const openAdd = () => {
    setEditTarget(null);
    setForm(EMPTY_FORM);
    setCoverPreview("");
    setFormOpen(true);
  };

  const openEdit = (book) => {
    setEditTarget(book);
    setForm({
      title: book.title,
      subtitle: book.subtitle,
      author: book.author,
      topic: book.topic,
      year: book.year,
      cover: null,
    });
    setCoverPreview(book.cover || "");
    setFormOpen(true);
  };

  const closeForm = () => {
    setFormOpen(false);
    setEditTarget(null);
    setForm(EMPTY_FORM);
    setCoverPreview("");
  };

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (name === "cover" && files?.[0]) {
      setForm((prev) => ({ ...prev, cover: files[0] }));
      setCoverPreview(URL.createObjectURL(files[0]));
    } else {
      setForm((prev) => ({ ...prev, [name]: value }));
    }
  };

  // ── Submit ─────────────────────────────────────────────────────────
  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      const data = new FormData();
      data.append("title", form.title.trim());
      data.append("subtitle", form.subtitle.trim());
      data.append("author", form.author.trim());
      data.append("topic", form.topic.trim());
      data.append("year", form.year);
      if (form.cover) data.append("cover", form.cover);

      if (editTarget) {
        await axios.put(
          `http://localhost:3005/api/books/update/${editTarget._id}`,
          data
        );
        toast.success("Book updated successfully");
      } else {
        await axios.post("http://localhost:3005/api/books/create", data);
        toast.success("Book added successfully");
      }

      closeForm();
      fetchBooks();
    } catch (err) {
      toast.error(err.response?.data?.message || "Operation failed");
    } finally {
      setSubmitting(false);
    }
  };

  // ── Delete ─────────────────────────────────────────────────────────
  const handleDelete = async () => {
    if (!deleteId) return;
    try {
      await axios.delete(`http://localhost:3005/api/books/delete/${deleteId}`);
      toast.success("Book deleted");
      setDeleteId(null);
      fetchBooks();
    } catch {
      toast.error("Failed to delete book");
    }
  };

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <BookOpen size={24} className="text-[#c9a84c]" />
            Manage Books
          </h2>
          <p className="text-gray-400 text-sm mt-1">
            {books.length} book{books.length !== 1 ? "s" : ""} total
          </p>
        </div>
        <button
          onClick={openAdd}
          className="flex items-center gap-2 bg-[#c9a84c] hover:bg-[#d8b45a] text-[#0d1b2a] px-4 py-2 rounded-lg font-semibold text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
        >
          <Plus size={16} />
          Add Book
        </button>
      </div>

      {/* Table */}
      {loading ? (
        <p className="text-gray-400 text-center py-16">Loading books...</p>
      ) : books.length === 0 ? (
        <p className="text-gray-500 text-center py-16">
          No books yet. Click "Add Book" to get started.
        </p>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-[#c9a84c]/20">
          <table className="w-full text-sm text-left" aria-label="Books table">
            <thead className="bg-[#0a0f1e] text-[#c9a84c] uppercase text-xs tracking-wider">
              <tr>
                <th className="px-4 py-3">Cover</th>
                <th className="px-4 py-3">Title</th>
                <th className="px-4 py-3">Author</th>
                <th className="px-4 py-3">Topic</th>
                <th className="px-4 py-3">Year</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#c9a84c]/10">
              {books.map((book) => (
                <tr
                  key={book._id}
                  className="bg-[#0d1b2a] hover:bg-[#0a0f1e] transition-colors"
                >
                  <td className="px-4 py-3">
                    {book.cover ? (
                      <img
                        src={book.cover}
                        alt={`Cover of ${book.title}`}
                        className="w-10 h-14 object-cover rounded"
                      />
                    ) : (
                      <div className="w-10 h-14 bg-[#c9a84c]/10 rounded flex items-center justify-center">
                        <BookOpen size={16} className="text-[#c9a84c]/40" />
                      </div>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    <p className="font-semibold text-white">{book.title}</p>
                    <p className="text-gray-500 text-xs mt-0.5">
                      {book.subtitle}
                    </p>
                  </td>
                  <td className="px-4 py-3 text-gray-300">{book.author}</td>
                  <td className="px-4 py-3 text-gray-300">{book.topic}</td>
                  <td className="px-4 py-3 text-gray-300">{book.year}</td>
                  <td className="px-4 py-3 text-right">
                    <div className="flex justify-end gap-2">
                      <button
                        onClick={() => openEdit(book)}
                        aria-label={`Edit ${book.title}`}
                        className="p-2 text-blue-400 hover:bg-blue-500/10 rounded-lg transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"
                      >
                        <Pencil size={15} />
                      </button>
                      <button
                        onClick={() => setDeleteId(book._id)}
                        aria-label={`Delete ${book.title}`}
                        className="p-2 text-red-400 hover:bg-red-500/10 rounded-lg transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-red-400"
                      >
                        <Trash2 size={15} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Add / Edit Form Modal */}
      <AnimatePresence>
        {formOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4"
            role="dialog"
            aria-modal="true"
            aria-labelledby="book-form-title"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-[#0d1b2a] border border-[#c9a84c]/30 rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between mb-5">
                <h3
                  id="book-form-title"
                  className="text-lg font-bold text-white"
                >
                  {editTarget ? "Edit Book" : "Add New Book"}
                </h3>
                <button
                  onClick={closeForm}
                  aria-label="Close form"
                  className="text-gray-400 hover:text-white transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c] rounded"
                >
                  <X size={20} />
                </button>
              </div>

              {/* Form */}
              <form onSubmit={handleSubmit} noValidate className="space-y-4">
                {/* Title */}
                <div>
                  <label
                    htmlFor="book-title"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Title <span aria-hidden="true" className="text-red-400">*</span>
                  </label>
                  <input
                    id="book-title"
                    name="title"
                    value={form.title}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. The Normal Christian Life"
                  />
                </div>

                {/* Subtitle */}
                <div>
                  <label
                    htmlFor="book-subtitle"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Subtitle <span aria-hidden="true" className="text-red-400">*</span>
                  </label>
                  <input
                    id="book-subtitle"
                    name="subtitle"
                    value={form.subtitle}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. A classic on the Christian walk"
                  />
                </div>

                {/* Author */}
                <div>
                  <label
                    htmlFor="book-author"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Author <span aria-hidden="true" className="text-red-400">*</span>
                  </label>
                  <input
                    id="book-author"
                    name="author"
                    value={form.author}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. Watchman Nee"
                  />
                </div>

                {/* Topic */}
                <div>
                  <label
                    htmlFor="book-topic"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Topic <span aria-hidden="true" className="text-red-400">*</span>
                  </label>
                  <input
                    id="book-topic"
                    name="topic"
                    value={form.topic}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. Spiritual Growth"
                  />
                </div>

                {/* Year */}
                <div>
                  <label
                    htmlFor="book-year"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Year <span aria-hidden="true" className="text-red-400">*</span>
                  </label>
                  <input
                    id="book-year"
                    name="year"
                    type="number"
                    min="1800"
                    max={new Date().getFullYear()}
                    value={form.year}
                    onChange={handleChange}
                    required
                    className="w-full bg-[#0a0f1e] border border-[#c9a84c]/30 text-white rounded-lg px-3 py-2 focus:outline-none focus:border-[#c9a84c] transition-colors"
                    placeholder="e.g. 1999"
                  />
                </div>

                {/* Cover Image */}
                <div>
                  <label
                    htmlFor="book-cover"
                    className="block text-sm text-gray-400 mb-1"
                  >
                    Cover Image{" "}
                    {editTarget && (
                      <span className="text-xs text-gray-500">
                        (leave empty to keep current)
                      </span>
                    )}
                  </label>
                  <label
                    htmlFor="book-cover"
                    className="flex items-center gap-3 cursor-pointer bg-[#0a0f1e] border border-dashed border-[#c9a84c]/40 rounded-lg px-3 py-3 hover:border-[#c9a84c] transition-colors"
                  >
                    {coverPreview ? (
                      <img
                        src={coverPreview}
                        alt="Cover preview"
                        className="w-12 h-16 object-cover rounded"
                      />
                    ) : (
                      <ImagePlus size={28} className="text-[#c9a84c]/50" />
                    )}
                    <span className="text-gray-400 text-sm">
                      {form.cover
                        ? form.cover.name
                        : coverPreview
                        ? "Click to change image"
                        : "Click to upload cover"}
                    </span>
                    <input
                      id="book-cover"
                      name="cover"
                      type="file"
                      accept="image/*"
                      onChange={handleChange}
                      className="sr-only"
                    />
                  </label>
                </div>

                {/* Actions */}
                <div className="flex gap-3 pt-2">
                  <button
                    type="button"
                    onClick={closeForm}
                    className="flex-1 border border-[#c9a84c]/30 text-gray-300 hover:text-white rounded-lg py-2 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="flex-1 bg-[#c9a84c] hover:bg-[#d8b45a] disabled:opacity-60 disabled:cursor-not-allowed text-[#0d1b2a] font-semibold rounded-lg py-2 text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                  >
                    {submitting
                      ? "Saving..."
                      : editTarget
                      ? "Update Book"
                      : "Add Book"}
                  </button>
                </div>
              </form>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Delete Confirm Modal */}
      <AnimatePresence>
        {deleteId && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4"
            role="dialog"
            aria-modal="true"
            aria-labelledby="delete-book-title"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-[#0d1b2a] border border-red-500/30 rounded-2xl p-6 w-full max-w-sm text-center"
            >
              <Trash2 size={36} className="text-red-400 mx-auto mb-3" />
              <h3
                id="delete-book-title"
                className="text-lg font-bold text-white mb-2"
              >
                Delete Book?
              </h3>
              <p className="text-gray-400 text-sm mb-5">
                This action cannot be undone.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => setDeleteId(null)}
                  className="flex-1 border border-[#c9a84c]/30 text-gray-300 hover:text-white rounded-lg py-2 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                >
                  Cancel
                </button>
                <button
                  onClick={handleDelete}
                  className="flex-1 bg-red-500 hover:bg-red-600 text-white font-semibold rounded-lg py-2 text-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-red-400"
                >
                  Yes, Delete
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
