// Generated by GitHub Copilot
const express = require("express");
const router = express.Router();
const upload = require("../Middleware/upload");

const {
  createArticle,
  getAllArticles,
  getArticleById,
  updateArticle,
  deleteArticle,
} = require("../Controller/articleController");

// Create Article
router.post("/create", upload.single("cover"), createArticle);

// Get All Articles
router.get("/all", getAllArticles);

// Get Single Article
router.get("/:id", getArticleById);

// Update Article
router.put("/update/:id", upload.single("cover"), updateArticle);

// Delete Article
router.delete("/delete/:id", deleteArticle);

module.exports = router;
