// Generated by GitHub Copilot
const Article = require("../Model/Article");
const cloudinary = require("../Config/cloudinary");
const streamifier = require("streamifier");

// ── Create Article ────────────────────────────────────────────────────────────
exports.createArticle = async (req, res) => {
  try {
    const { title, body, author, category, date } = req.body;

    let coverUrl = "";

    // Upload Image First (same pattern as believerController)
    if (req.file) {
      const streamUpload = (req) => {
        return new Promise((resolve, reject) => {
          const stream = cloudinary.uploader.upload_stream(
            { folder: "PBM_Church_Articles" },
            (error, result) => {
              if (result) {
                resolve(result);
              } else {
                reject(error);
              }
            },
          );
          streamifier.createReadStream(req.file.buffer).pipe(stream);
        });
      };

      const result = await streamUpload(req);
      coverUrl = result.secure_url;
    }

    // Create Article with cover already set
    const newArticle = await Article.create({
      title,
      body,
      author,
      category,
      date: date || Date.now(),
      cover: coverUrl,
    });

    res.status(201).json({
      success: true,
      message: "Article created successfully",
      data: newArticle,
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Get All Articles ──────────────────────────────────────────────────────────
exports.getAllArticles = async (req, res) => {
  try {
    const articles = await Article.find().sort({ createdAt: -1 });
    res.status(200).json({
      success: true,
      count: articles.length,
      data: articles,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Get Single Article ────────────────────────────────────────────────────────
exports.getArticleById = async (req, res) => {
  try {
    const article = await Article.findById(req.params.id);
    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }
    res.status(200).json({ success: true, data: article });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Update Article ────────────────────────────────────────────────────────────
exports.updateArticle = async (req, res) => {
  try {
    const updatedData = { ...req.body };

    // Upload New Cover (same pattern as believerController)
    if (req.file) {
      const streamUpload = (req) => {
        return new Promise((resolve, reject) => {
          const stream = cloudinary.uploader.upload_stream(
            { folder: "PBM_Church_Articles" },
            (error, result) => {
              if (result) {
                resolve(result);
              } else {
                reject(error);
              }
            },
          );
          streamifier.createReadStream(req.file.buffer).pipe(stream);
        });
      };

      const result = await streamUpload(req);
      updatedData.cover = result.secure_url;
    }

    const article = await Article.findByIdAndUpdate(
      req.params.id,
      updatedData,
      { new: true, runValidators: true }
    );

    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }

    res.status(200).json({
      success: true,
      message: "Article updated successfully",
      data: article,
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Delete Article ────────────────────────────────────────────────────────────
exports.deleteArticle = async (req, res) => {
  try {
    const article = await Article.findByIdAndDelete(req.params.id);
    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }
    res
      .status(200)
      .json({ success: true, message: "Article deleted successfully" });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
