// Generated by GitHub Copilot
const Article = require("../Model/Article");
const cloudinary = require("../Config/cloudinary");
const streamifier = require("streamifier");

/**
 * Helper — upload a buffer to Cloudinary and return the secure URL.
 * @param {Buffer} buffer - File buffer from multer memoryStorage.
 * @param {string} folder - Cloudinary folder path.
 * @returns {Promise<string>} Secure URL of the uploaded image.
 */
const uploadToCloudinary = (buffer, folder) => {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder },
      (error, result) => {
        if (result) {
          resolve(result.secure_url);
        } else {
          reject(error);
        }
      }
    );
    streamifier.createReadStream(buffer).pipe(stream);
  });
};

// ── Create Article ────────────────────────────────────────────────────────────
exports.createArticle = async (req, res) => {
  try {
    const { title, body, author, category, date } = req.body;

    const newArticle = await Article.create({
      title,
      body,
      author,
      category,
      date: date || Date.now(),
    });

    if (req.file) {
      const coverUrl = await uploadToCloudinary(
        req.file.buffer,
        "PBM_Church_Articles"
      );
      newArticle.cover = coverUrl;
      await newArticle.save();
    }

    res.status(201).json({
      success: true,
      message: "Article created successfully",
      data: newArticle,
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Get All Articles ──────────────────────────────────────────────────────────
exports.getAllArticles = async (req, res) => {
  try {
    const articles = await Article.find().sort({ createdAt: -1 });
    res.status(200).json({
      success: true,
      count: articles.length,
      data: articles,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Get Single Article ────────────────────────────────────────────────────────
exports.getArticleById = async (req, res) => {
  try {
    const article = await Article.findById(req.params.id);
    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }
    res.status(200).json({ success: true, data: article });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Update Article ────────────────────────────────────────────────────────────
exports.updateArticle = async (req, res) => {
  try {
    const updatedData = { ...req.body };

    if (req.file) {
      updatedData.cover = await uploadToCloudinary(
        req.file.buffer,
        "PBM_Church_Articles"
      );
    }

    const article = await Article.findByIdAndUpdate(
      req.params.id,
      updatedData,
      { new: true, runValidators: true }
    );

    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }

    res.status(200).json({
      success: true,
      message: "Article updated successfully",
      data: article,
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// ── Delete Article ────────────────────────────────────────────────────────────
exports.deleteArticle = async (req, res) => {
  try {
    const article = await Article.findByIdAndDelete(req.params.id);
    if (!article) {
      return res
        .status(404)
        .json({ success: false, message: "Article not found" });
    }
    res
      .status(200)
      .json({ success: true, message: "Article deleted successfully" });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
