// Generated by GitHub Copilot
import { useState, useCallback, useEffect } from "react";
import { motion } from "framer-motion";
import useEmblaCarousel from "embla-carousel-react";
import { ChevronLeft, ChevronRight, Calendar, ExternalLink } from "lucide-react";

// Placeholder data — replace with real data or API calls
const featuredEvents = [
  {
    id: 1,
    title: "Annual Youth Conference 2026",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 2,
    title: "Women's Prayer Retreat",
    image: "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 3,
    title: "Christmas Worship Night",
    image: "https://images.unsplash.com/photo-1510590337019-5ef8d3d32116?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 4,
    title: "Friday Gathering — Nagullanka",
    image: "https://images.unsplash.com/photo-1504777315-0b0c6d1b3f1e?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 5,
    title: "Saturday Gathering — Marteru",
    image: "https://images.unsplash.com/photo-1509223197845-458d87318791?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 6,
    title: "Sunday Service — Nagullanka (11:00 AM)",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=500&fit=crop",
    link: "#",
  },
  {
    id: 7,
    title: "Early Sunday Worship — Marteru (8:00 AM)",
    image: "https://images.unsplash.com/photo-1504349729854-5a3f1a2cc2b7?w=1200&h=500&fit=crop",
    link: "#",
  },
];

const upcomingEvents = [
  {
    id: 1,
    title: "Sunday Worship Service",
    date: "Every Sunday, 10:00 AM",
    description: "Join us for a time of praise, prayer, and the preaching of God's Word.",
    link: "#",
  },
  {
    id: 2,
    title: "Mid-Week Bible Study",
    date: "Every Wednesday, 7:00 PM",
    description: "Dive deeper into Scripture with our community in an interactive study.",
    link: "#",
  },
  {
    id: 3,
    title: "Youth Fellowship Night",
    date: "June 7, 2026 – 6:00 PM",
    description: "A special evening of worship, games, and fellowship for the youth.",
    link: "#",
  },
  {
    id: 4,
    title: "Community Outreach Program",
    date: "June 14, 2026 – 9:00 AM",
    description: "Serving our neighborhood with food distribution and prayer support.",
    link: "#",
  },
  // Recurring local gatherings
  {
    id: 5,
    title: "Friday Gathering — Nagullanka",
    date: "Every Friday, 10:00 AM – 1:00 PM — Nagullanka",
    description: "Weekly fellowship and teaching at Nagullanka.",
    link: "#",
  },
  {
    id: 6,
    title: "Saturday Gathering — Marteru",
    date: "Every Saturday, 10:00 AM – 1:00 PM — Marteru",
    description: "Weekly worship and community meeting at Marteru.",
    link: "#",
  },
  {
    id: 7,
    title: "Sunday Morning — Nagullanka",
    date: "Every Sunday, 11:00 AM – 1:30 PM — Nagullanka",
    description: "Sunday worship service at Nagullanka.",
    link: "#",
  },
  {
    id: 8,
    title: "Sunday Early Worship — Marteru",
    date: "Every Sunday, 8:00 AM – 10:00 AM — Marteru",
    description: "Early morning service at Marteru.",
    link: "#",
  },
];

const recentEvents = [
  {
    id: 1,
    title: "Easter Celebration Service",
    date: "April 20, 2026",
    description: "A powerful resurrection Sunday service with special worship and baptisms.",
    link: "#",
  },
  {
    id: 2,
    title: "Good Friday Service",
    date: "April 18, 2026",
    description: "A solemn remembrance of the sacrifice of Jesus Christ on the cross.",
    link: "#",
  },
  {
    id: 3,
    title: "Church Anniversary Celebration",
    date: "March 15, 2026",
    description: "Celebrating God's faithfulness through the years of PBM Church.",
    link: "#",
  },
  {
    id: 4,
    title: "Men's Prayer Breakfast",
    date: "March 1, 2026",
    description: "Fellowship and intercession over breakfast for the men of the church.",
    link: "#",
  },
];

function FeaturedCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true });
  const [selectedIndex, setSelectedIndex] = useState(0);

  const onSelect = useCallback(() => {
    if (!emblaApi) return;
    setSelectedIndex(emblaApi.selectedScrollSnap());
  }, [emblaApi]);

  useEffect(() => {
    if (!emblaApi) return;
    emblaApi.on("select", onSelect);
    onSelect();
  }, [emblaApi, onSelect]);

  const scrollPrev = useCallback(() => emblaApi?.scrollPrev(), [emblaApi]);
  const scrollNext = useCallback(() => emblaApi?.scrollNext(), [emblaApi]);
  const scrollTo = useCallback((index) => emblaApi?.scrollTo(index), [emblaApi]);

  return (
    <div className="relative rounded-2xl overflow-hidden mb-16 border border-[#c9a84c]/20">
      <div className="overflow-hidden" ref={emblaRef}>
        <div className="flex">
          {featuredEvents.map((event) => (
            <div key={event.id} className="flex-[0_0_100%] min-w-0 relative">
              <a
                href={event.link}
                target="_blank"
                rel="noopener noreferrer"
                className="block"
                aria-label={`View details for ${event.title}`}
              >
                <div className="relative h-[300px] md:h-[450px]">
                  <img
                    src={event.image}
                    alt={event.title}
                    className="w-full h-full object-cover"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-[#0a0f1e]/90 via-transparent to-transparent" />
                  <div className="absolute bottom-8 left-8 right-8">
                    <h3 className="text-2xl md:text-4xl font-cinzel font-bold text-white drop-shadow-lg">
                      {event.title}
                    </h3>
                  </div>
                </div>
              </a>
            </div>
          ))}
        </div>
      </div>

      {/* Navigation Arrows */}
      <button
        onClick={scrollPrev}
        className="absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-[#0a0f1e]/70 border border-[#c9a84c]/30 rounded-full flex items-center justify-center text-[#c9a84c] hover:bg-[#c9a84c]/20 transition-colors"
        aria-label="Previous slide"
      >
        <ChevronLeft size={20} />
      </button>
      <button
        onClick={scrollNext}
        className="absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 bg-[#0a0f1e]/70 border border-[#c9a84c]/30 rounded-full flex items-center justify-center text-[#c9a84c] hover:bg-[#c9a84c]/20 transition-colors"
        aria-label="Next slide"
      >
        <ChevronRight size={20} />
      </button>

      {/* Dot Indicators */}
      <div className="absolute bottom-3 left-1/2 -translate-x-1/2 flex gap-2">
        {featuredEvents.map((_, idx) => (
          <button
            key={idx}
            onClick={() => scrollTo(idx)}
            className={`w-3 h-3 rounded-full transition-all duration-300 ${
              idx === selectedIndex
                ? "bg-[#c9a84c] scale-110"
                : "bg-white/40 hover:bg-white/60"
            }`}
            aria-label={`Go to slide ${idx + 1}`}
          />
        ))}
      </div>
    </div>
  );
}

function EventCarousel({ events }) {
  const [emblaRef, emblaApi] = useEmblaCarousel({
    loop: false,
    align: "start",
    slidesToScroll: 1,
    breakpoints: {
      "(min-width: 768px)": { slidesToScroll: 2 },
    },
  });
  const [canScrollPrev, setCanScrollPrev] = useState(false);
  const [canScrollNext, setCanScrollNext] = useState(true);

  const onSelect = useCallback(() => {
    if (!emblaApi) return;
    setCanScrollPrev(emblaApi.canScrollPrev());
    setCanScrollNext(emblaApi.canScrollNext());
  }, [emblaApi]);

  useEffect(() => {
    if (!emblaApi) return;
    emblaApi.on("select", onSelect);
    emblaApi.on("reInit", onSelect);
    onSelect();
  }, [emblaApi, onSelect]);

  const scrollPrev = useCallback(() => emblaApi?.scrollPrev(), [emblaApi]);
  const scrollNext = useCallback(() => emblaApi?.scrollNext(), [emblaApi]);

  return (
    <div className="relative">
      <div className="overflow-hidden" ref={emblaRef}>
        <div className="flex gap-6">
          {events.map((event) => (
            <div
              key={event.id}
              className="flex-[0_0_100%] md:flex-[0_0_calc(50%-12px)] lg:flex-[0_0_calc(33.333%-16px)] min-w-0"
            >
              <div className="bg-[#0a0f1e] border border-[#c9a84c]/20 rounded-xl p-6 h-full flex flex-col hover:-translate-y-1 transition-transform duration-300 group">
                <div className="flex items-center gap-2 text-[#c9a84c] text-sm mb-3">
                  <Calendar size={16} />
                  <span>{event.date}</span>
                </div>
                <h4 className="text-xl font-cinzel font-bold text-white mb-3 group-hover:text-[#c9a84c] transition-colors">
                  {event.title}
                </h4>
                <p className="text-gray-400 leading-relaxed flex-1 mb-4">
                  {event.description}
                </p>
                <a
                  href={event.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-[#c9a84c] hover:text-[#e0c068] text-sm font-semibold transition-colors"
                  aria-label={`Learn more about ${event.title}`}
                >
                  Learn More <ExternalLink size={14} />
                </a>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Carousel Arrows */}
      {(canScrollPrev || canScrollNext) && (
        <div className="flex justify-end gap-2 mt-4">
          <button
            onClick={scrollPrev}
            disabled={!canScrollPrev}
            className="w-9 h-9 bg-[#0a0f1e] border border-[#c9a84c]/30 rounded-full flex items-center justify-center text-[#c9a84c] hover:bg-[#c9a84c]/20 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
            aria-label="Previous events"
          >
            <ChevronLeft size={18} />
          </button>
          <button
            onClick={scrollNext}
            disabled={!canScrollNext}
            className="w-9 h-9 bg-[#0a0f1e] border border-[#c9a84c]/30 rounded-full flex items-center justify-center text-[#c9a84c] hover:bg-[#c9a84c]/20 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
            aria-label="Next events"
          >
            <ChevronRight size={18} />
          </button>
        </div>
      )}
    </div>
  );
}

export default function Events() {
  const [activeTab, setActiveTab] = useState("upcoming");

  const tabs = [
    { key: "upcoming", label: "Upcoming" },
    { key: "recent", label: "Recent" },
  ];

  return (
    <section id="events" className="py-24 bg-[#0d1b2a] relative">
      <div className="container mx-auto px-6">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <span className="text-[#c9a84c] font-cinzel uppercase tracking-[0.2em] text-sm font-bold block mb-3">
              What&apos;s Happening
            </span>
            <h2 className="text-4xl md:text-5xl font-cinzel font-bold text-white mb-4">
              Events
            </h2>
            <p className="text-gray-300 text-lg max-w-2xl mx-auto">
              Stay connected with our church community through worship gatherings,
              outreach programs, and fellowship events.
            </p>
          </motion.div>

          {/* Featured Events Banner Carousel */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <FeaturedCarousel />
          </motion.div>

          {/* Tabs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.3 }}
          >
            <div className="flex items-center gap-1 mb-8 bg-[#0a0f1e] border border-[#c9a84c]/20 rounded-lg p-1 w-fit" role="tablist">
              {tabs.map((tab) => (
                <button
                  key={tab.key}
                  role="tab"
                  aria-selected={activeTab === tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className={`px-6 py-2.5 rounded-md text-sm font-semibold uppercase tracking-wider transition-all duration-300 ${
                    activeTab === tab.key
                      ? "bg-[#c9a84c] text-[#0a0f1e]"
                      : "text-gray-400 hover:text-white"
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Tab Content */}
            <div role="tabpanel">
              {activeTab === "upcoming" && <EventCarousel events={upcomingEvents} />}
              {activeTab === "recent" && <EventCarousel events={recentEvents} />}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
