// Generated by GitHub Copilot
import { useState, useEffect } from "react";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, Search, X, User, Calendar, Tag } from "lucide-react";

/**
 * Articles public page.
 * Fetches articles from /api/articles/all and renders a searchable,
 * filterable grid matching the site's dark gold theme.
 */
export default function Articles() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");
  const [selectedArticle, setSelectedArticle] = useState(null);

  useEffect(() => {
    const fetchArticles = async () => {
      try {
        const res = await axios.get("http://localhost:3005/api/articles/all");
        setArticles(res.data.data || []);
      } catch {
        setError("Failed to load articles. Please try again later.");
      } finally {
        setLoading(false);
      }
    };
    fetchArticles();
  }, []);

  const categories = [
    "All",
    ...new Set(articles.map((a) => a.category).filter(Boolean)),
  ];

  const filtered = articles.filter((article) => {
    const q = searchQuery.toLowerCase();
    const matchesSearch =
      article.title?.toLowerCase().includes(q) ||
      article.author?.toLowerCase().includes(q) ||
      article.body?.toLowerCase().includes(q);
    const matchesCategory =
      activeCategory === "All" || article.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <section className="min-h-screen bg-[#FFFDF5] pt-28 pb-20 px-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-12"
      >
        <div className="flex justify-center mb-4">
          <BookOpen size={48} className="text-[#c9a84c]" aria-hidden="true" />
        </div>
        <h1 className="text-4xl md:text-5xl font-cinzel font-bold text-[#c9a84c] mb-4">
          Articles
        </h1>
        <p className="text-[#33275A] max-w-xl mx-auto text-base">
          Writings and reflections to strengthen your faith and deepen your
          walk with God.
        </p>
        <div className="w-20 h-1 bg-[#c9a84c] mx-auto mt-6 rounded-full"></div>
      </motion.div>

      {/* Loading / Error */}
      {loading && (
        <p className="text-center text-[#33275A] py-16">Loading articles...</p>
      )}
      {error && (
        <p className="text-center text-red-400 py-16" role="alert">
          {error}
        </p>
      )}

      {!loading && !error && (
        <>
          {/* Search */}
          <div className="max-w-md mx-auto mb-8 relative">
            <Search
              size={16}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-[#c9a84c]/60"
              aria-hidden="true"
            />
            <label htmlFor="article-search" className="sr-only">
              Search articles
            </label>
            <input
              id="article-search"
              type="search"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search articles..."
              className="w-full pl-9 pr-4 py-3 bg-white border border-[#c9a84c]/50 rounded-lg text-[#1E1535] placeholder-gray-500 focus:outline-none focus:border-[#c9a84c] transition-colors"
            />
          </div>

          {/* Category Filter */}
          <div
            className="flex flex-wrap justify-center gap-3 mb-10"
            role="group"
            aria-label="Filter by category"
          >
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-4 py-2 rounded-full text-sm uppercase tracking-wider transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c] ${
                  activeCategory === cat
                    ? "bg-[#c9a84c] text-[#0d1b2a] font-semibold"
                    : "border border-[#c9a84c]/40 text-[#33275A] hover:border-[#c9a84c] hover:text-[#c9a84c]"
                }`}
                aria-pressed={activeCategory === cat}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* Articles Grid */}
          <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filtered.length > 0 ? (
              filtered.map((article, idx) => (
                <motion.article
                  key={article._id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: idx * 0.07 }}
                  className="bg-white border border-[#c9a84c]/40 rounded-xl overflow-hidden hover:border-[#c9a84c]/60 hover:shadow-lg hover:shadow-[#c9a84c]/5 transition-all flex flex-col cursor-pointer"
                  onClick={() => setSelectedArticle(article)}
                >
                  {/* Cover image */}
                  {article.cover && (
                    <img
                      src={article.cover}
                      alt={`Cover for ${article.title}`}
                      className="w-full h-40 object-cover"
                    />
                  )}
                  <div className="p-6 flex flex-col flex-1">
                    <span className="inline-block text-xs uppercase tracking-widest text-[#c9a84c] bg-[#c9a84c]/10 px-3 py-1 rounded-full mb-3 self-start">
                      {article.category}
                    </span>
                    <h2 className="text-lg font-cinzel font-semibold text-[#1E1535] mb-2 leading-snug">
                      {article.title}
                    </h2>
                    <p className="text-[#33275A] text-sm mb-4 leading-relaxed line-clamp-3 flex-1">
                      {article.body}
                    </p>
                    <div className="flex justify-between items-center text-xs text-gray-500 border-t border-[#c9a84c]/10 pt-3 mt-auto">
                      <span>{article.author}</span>
                      <time dateTime={article.date}>
                        {new Date(article.date).toLocaleDateString("en-US", {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                        })}
                      </time>
                    </div>
                    <button
                      className="mt-4 text-xs text-[#c9a84c] border border-[#c9a84c]/40 rounded-lg py-2 hover:bg-[#c9a84c]/10 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c]"
                      onClick={(e) => { e.stopPropagation(); setSelectedArticle(article); }}
                      aria-label={`Read full article: ${article.title}`}
                    >
                      Read Full Article
                    </button>
                  </div>
                </motion.article>
              ))
            ) : (
              <p className="col-span-full text-center text-gray-500 py-12">
                No articles found matching your search.
              </p>
            )}
          </div>
        </>
      )}

      {/* ── Article Read Modal ── */}
      <AnimatePresence>
        {selectedArticle && (
          <motion.div
            key="article-modal-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm px-4 py-8"
            onClick={() => setSelectedArticle(null)}
            role="dialog"
            aria-modal="true"
            aria-label={selectedArticle.title}
          >
            <motion.div
              key="article-modal-panel"
              initial={{ opacity: 0, y: 40, scale: 0.97 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 40, scale: 0.97 }}
              transition={{ duration: 0.3 }}
              className="bg-white border border-[#c9a84c]/50 rounded-2xl w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden shadow-2xl shadow-black/60"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Cover */}
              {selectedArticle.cover && (
                <img
                  src={selectedArticle.cover}
                  alt={`Cover for ${selectedArticle.title}`}
                  className="w-full h-56 object-cover flex-shrink-0"
                />
              )}

              {/* Scrollable body */}
              <div className="flex flex-col flex-1 overflow-y-auto p-8">
                {/* Header row */}
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div className="flex-1">
                    <span className="inline-block text-xs uppercase tracking-widest text-[#c9a84c] bg-[#c9a84c]/10 px-3 py-1 rounded-full mb-3">
                      <Tag size={10} className="inline mr-1" aria-hidden="true" />
                      {selectedArticle.category}
                    </span>
                    <h2 className="text-2xl font-cinzel font-bold text-[#1E1535] leading-snug">
                      {selectedArticle.title}
                    </h2>
                  </div>
                  <button
                    onClick={() => setSelectedArticle(null)}
                    className="text-[#33275A] hover:text-[#1E1535] transition-colors flex-shrink-0 mt-1 focus:outline-none focus-visible:ring-2 focus-visible:ring-[#c9a84c] rounded"
                    aria-label="Close article"
                  >
                    <X size={22} />
                  </button>
                </div>

                {/* Meta */}
                <div className="flex items-center gap-5 text-sm text-gray-500 mb-6 pb-4 border-b border-[#c9a84c]/10">
                  <span className="flex items-center gap-1.5">
                    <User size={13} aria-hidden="true" />
                    {selectedArticle.author}
                  </span>
                  <time
                    dateTime={selectedArticle.date}
                    className="flex items-center gap-1.5"
                  >
                    <Calendar size={13} aria-hidden="true" />
                    {new Date(selectedArticle.date).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </time>
                </div>

                {/* Full body */}
                <p className="text-[#33275A] text-base leading-relaxed whitespace-pre-wrap">
                  {selectedArticle.body}
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}






